"""Alembic 迁移测试

守的是**迁移与模型不漂移**这一条。最容易犯的错是改了 `backend/db/models.py`
却忘了生成迁移：本地跑 `create_all` 一切正常，部署时 `alembic upgrade head`
建出的是旧表，然后在生产上以"列不存在"的形式暴露。

`alembic check` 就是为此存在的：它拿模型元数据与已迁移的库做 diff，
有差异就非零退出。把它放进测试，漂移在 CI 就被拦住而不是在部署时。

这几条测试比其余单测慢（每条都要真建一遍库），但它们替代的是
"部署到一半发现表不对"这种代价。
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# 与 M2 计划书表结构一节一一对应。
# 这里写死表名而不是从 metadata 反推：反推的话模型删了表测试也跟着"通过"，
# 而删表是需要有人显式确认的动作。
EXPECTED_TABLES = {
    "sessions", "messages",
    "runs", "run_steps", "tool_calls", "evidence", "citations",
    "feedback", "eval_runs", "eval_results",
    "ingest_tasks",
}


@pytest.fixture
def alembic_cfg(monkeypatch, tmp_path: Path) -> Config:
    """指向临时 SQLite 的 alembic 配置。

    `alembic/env.py` 在调用时才读 `config.DATABASE_URL`，
    因此 monkeypatch 能生效 —— 它 `import config` 拿到的是
    sys.modules 里同一个模块对象。

    script_location 用绝对路径：相对路径依赖 pytest 的启动目录，
    从别的目录跑就找不到迁移脚本。
    """
    import config

    db_path = tmp_path / "migrate.db"
    monkeypatch.setattr(
        config, "DATABASE_URL", f"sqlite+aiosqlite:///{db_path.as_posix()}"
    )

    cfg = Config(str(PROJECT_ROOT / "alembic.ini"))
    cfg.set_main_option("script_location", str(PROJECT_ROOT / "alembic"))
    cfg.attributes["_test_db_path"] = db_path
    return cfg


def table_names(db_path: Path) -> set[str]:
    with sqlite3.connect(db_path) as conn:
        return {
            row[0] for row in conn.execute(
                "select name from sqlite_master where type='table'"
            )
        }


class TestUpgrade:
    def test_upgrade_head_creates_all_tables(self, alembic_cfg):
        """C2：`alembic upgrade head` 建出全部表。"""
        command.upgrade(alembic_cfg, "head")

        got = table_names(alembic_cfg.attributes["_test_db_path"])
        assert EXPECTED_TABLES <= got, f"缺表: {EXPECTED_TABLES - got}"
        assert "alembic_version" in got, "版本表缺失，迁移状态无处记录"

    def test_primary_key_is_integer_on_sqlite(self, alembic_cfg):
        """SQLite 上自增主键必须落成 INTEGER。

        回归测试：BigInteger 渲染成 BIGINT 时不是 rowid 别名，
        插入会报 "NOT NULL constraint failed"。models.py 用
        `BigInteger().with_variant(Integer, "sqlite")` 解决，
        这条守住迁移里也带着该变体 —— 只修模型不修迁移的话，
        create_all 建的库能用，迁移建的库不能用。
        """
        command.upgrade(alembic_cfg, "head")
        db_path = alembic_cfg.attributes["_test_db_path"]

        with sqlite3.connect(db_path) as conn:
            for table in ("runs", "messages", "run_steps", "tool_calls",
                          "evidence", "citations", "feedback",
                          "eval_runs", "eval_results"):
                col_type = conn.execute(
                    f"select type from pragma_table_info('{table}') where name='id'"
                ).fetchone()[0]
                assert col_type == "INTEGER", f"{table}.id 是 {col_type}，自增会失效"

    def test_inserting_without_id_works_after_migration(self, alembic_cfg):
        """迁移建出的表能真的写进去。

        只断言"表存在"不够 —— 上面那个主键 bug 恰恰是表建得出来、
        写不进去。这条直接插一行。
        """
        command.upgrade(alembic_cfg, "head")
        db_path = alembic_cfg.attributes["_test_db_path"]

        with sqlite3.connect(db_path) as conn:
            conn.execute(
                "insert into runs (trace_id, query, status, created_at) "
                "values ('t1', 'q', 'running', '2026-01-01 00:00:00')"
            )
            row_id = conn.execute("select id from runs").fetchone()[0]
        assert row_id == 1


class TestNoDrift:
    def test_models_match_migrations(self, alembic_cfg):
        """`alembic check` —— 模型与迁移无差异。

        这是本文件最重要的一条。它失败的含义是：有人改了
        `backend/db/models.py` 但没跑
        `alembic revision --autogenerate`。修法是生成迁移并人工审阅，
        **不是**改这条测试。

        已知局限：autogenerate 检测不到表/列改名（会看成删+建），
        也检测不到 CHECK 约束变化。check 通过不等于迁移绝对正确。
        """
        command.upgrade(alembic_cfg, "head")
        try:
            command.check(alembic_cfg)
        except AutogenerateDiffsDetected as exc:
            pytest.fail(
                "模型与迁移不一致，需要生成新迁移：\n"
                f"{exc}\n"
                "  venv/Scripts/python.exe -m alembic revision --autogenerate -m \"说明\""
            )


class TestDowngrade:
    def test_downgrade_base_removes_all_tables(self, alembic_cfg):
        """回退能走通。

        写了 downgrade 却从没跑过，等于没有回退路径 ——
        真出问题时才发现它报错，那时正是最不想调试的时刻。
        """
        command.upgrade(alembic_cfg, "head")
        command.downgrade(alembic_cfg, "base")

        got = table_names(alembic_cfg.attributes["_test_db_path"])
        assert not (EXPECTED_TABLES & got), f"未清掉: {EXPECTED_TABLES & got}"

    def test_upgrade_downgrade_upgrade_is_clean(self, alembic_cfg):
        """升-降-升不留残留。

        SQLite 上迁移以 batch 模式执行（建新表、拷数据、删旧表、改名），
        中途失败会留下 `_alembic_tmp_*` 这类临时表。
        这条确保来回走一遍是干净的。
        """
        command.upgrade(alembic_cfg, "head")
        command.downgrade(alembic_cfg, "base")
        command.upgrade(alembic_cfg, "head")

        got = table_names(alembic_cfg.attributes["_test_db_path"])
        assert EXPECTED_TABLES <= got
        leftovers = {t for t in got if t.startswith("_alembic_tmp")}
        assert not leftovers, f"残留临时表: {leftovers}"


class TestConfig:
    def test_ini_is_ascii_only(self):
        """`alembic.ini` 必须纯 ASCII。

        configparser 以 `encoding="locale"` 读它 —— Windows 上是 GBK，
        文件里有中文会在 alembic 启动前抛 UnicodeDecodeError，
        而报错栈指向 configparser 内部，看不出是编码问题。
        说明写在 alembic/README.md 里。
        """
        raw = (PROJECT_ROOT / "alembic.ini").read_bytes()
        try:
            raw.decode("ascii")
        except UnicodeDecodeError as exc:
            pytest.fail(f"alembic.ini 含非 ASCII 字节（位置 {exc.start}）")

    def test_ini_has_no_hardcoded_url(self):
        """数据库地址不写在 ini 里。

        两个理由：config.py 是配置唯一入口（CLAUDE.md 架构约束）；
        以及这样 ini 里不含密码，可以安全提交。
        """
        text = (PROJECT_ROOT / "alembic.ini").read_text(encoding="ascii")
        active = [
            line for line in text.splitlines()
            if line.strip().startswith("sqlalchemy.url")
        ]
        assert not active, f"ini 里有写死的连接串: {active}"
