"""init schema

M2 首个迁移：可追溯轨迹的 11 张表。

autogenerate 生成后人工补了 `import backend.db.models` —— 它把自定义类型
渲染成全限定名（`backend.db.models.JSONField()`），却不会自动加上对应的
import，直接跑会 NameError。这是 autogenerate 产物必须人工审阅的典型例子。

引用模型模块意味着迁移与模型代码耦合：日后若删掉 JSONField/UtcDateTime，
这个历史迁移会失效。届时正确做法是把类型定义就地内联进本文件，
而不是改模型去迁就它 —— 迁移记录的是"当时的形状"。

Revision ID: 85b38f6f3e90
Revises:
Create Date: 2026-08-14 00:27:45.456494

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import backend.db.models


revision: str = '85b38f6f3e90'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('suite', sa.String(length=64), nullable=False),
    sa.Column('variant', sa.String(length=64), nullable=False),
    sa.Column('started_at', backend.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', backend.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('meta', backend.db.models.JSONField(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingest_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', backend.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', backend.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingest_tasks', schema=None) as batch_op:
        batch_op.create_index('ix_ingest_tasks_status', ['status', 'created_at'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', backend.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', backend.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('meta', backend.db.models.JSONField(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_last_active_at'), ['last_active_at'], unique=False)

    op.create_table('eval_results',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('eval_run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('qid', sa.String(length=64), nullable=False),
    sa.Column('metrics', backend.db.models.JSONField(), nullable=False),
    sa.ForeignKeyConstraint(['eval_run_id'], ['eval_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eval_results', schema=None) as batch_op:
        batch_op.create_index('ix_eval_results_run_qid', ['eval_run_id', 'qid'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('route', sa.String(length=32), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_ms', sa.Integer(), nullable=True),
    sa.Column('first_token_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', backend.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', backend.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index('ix_runs_created_desc', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_trace_id'), ['trace_id'], unique=True)

    op.create_table('evidence',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('chunk_id', sa.String(length=128), nullable=False),
    sa.Column('file', sa.String(length=512), nullable=True),
    sa.Column('relevance', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('retrieved_by', sa.String(length=64), nullable=True),
    sa.Column('used_in_answer', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_chunk', ['chunk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_run_id'), ['run_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', backend.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_session_created', ['session_id', 'created_at'], unique=False)

    op.create_table('run_steps',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('node', sa.String(length=64), nullable=False),
    sa.Column('ms', sa.Integer(), nullable=True),
    sa.Column('state_snapshot', backend.db.models.JSONField(), nullable=False),
    sa.Column('created_at', backend.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'seq', name='uq_run_steps_run_seq')
    )
    with op.batch_alter_table('run_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_steps_run_id'), ['run_id'], unique=False)

    op.create_table('tool_calls',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('tool', sa.String(length=64), nullable=False),
    sa.Column('args', backend.db.models.JSONField(), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('ms', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', backend.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'seq', name='uq_tool_calls_run_seq')
    )
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.create_index('ix_tool_calls_key', ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_calls_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_tool_calls_tool_ok', ['tool', 'ok'], unique=False)

    op.create_table('citations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('sentence_idx', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.String(length=128), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verify_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.create_index('ix_citations_message', ['message_id', 'sentence_idx'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', backend.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_message_id'))

    op.drop_table('feedback')
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.drop_index('ix_citations_message')

    op.drop_table('citations')
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.drop_index('ix_tool_calls_tool_ok')
        batch_op.drop_index(batch_op.f('ix_tool_calls_run_id'))
        batch_op.drop_index('ix_tool_calls_key')

    op.drop_table('tool_calls')
    with op.batch_alter_table('run_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_steps_run_id'))

    op.drop_table('run_steps')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_session_created')

    op.drop_table('messages')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_run_id'))
        batch_op.drop_index('ix_evidence_chunk')

    op.drop_table('evidence')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_trace_id'))
        batch_op.drop_index('ix_runs_created_desc')

    op.drop_table('runs')
    with op.batch_alter_table('eval_results', schema=None) as batch_op:
        batch_op.drop_index('ix_eval_results_run_qid')

    op.drop_table('eval_results')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_last_active_at'))

    op.drop_table('sessions')
    with op.batch_alter_table('ingest_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_ingest_tasks_status')

    op.drop_table('ingest_tasks')
    op.drop_table('eval_runs')
    # ### end Alembic commands ###
